# Generated by Django 4.0.2 on 2022-03-02 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=40)),
                ('ename', models.TextField(max_length=100)),
                ('role', models.TextField(max_length=100)),
                ('email', models.TextField()),
            ],
        ),
    ]
